### ISSUE TITLE
关于用Diffusion合成数据集的一些问题

### ISSUE THREAD

**Issue by NBningjia** [Yasoz/SynthTraj#1]
您好！首先祝贺您首次提出了使用Diffusion生成时空轨迹的方法，在拜读了您的论文以及下载了您的数据集参考后，我产生了几个问题想向您请教一下，恳请得到您的回答！
问：
1. 我下载了其中一个西安城市的轨迹数据集，发现将所有轨迹可视化出来后，第1183条轨迹存在着点与点之间经纬度跨度大、且各点呈现不规律的散点分布，请问是原本数据集中本就存在无序的点，还是说diffusion在生成过程中的缺陷导致的？
2. 请问生成的数据集和原始数据集属于同一个分布的情况下，生成的轨迹具体数值是否和原始轨迹具体数据一致？
3. 请问作者在设计噪声预测网络时为什么选用了ResNet的设计，而不使用U-Net作为噪声预测网络呢？

**Comment by Yasoz** [comment]
谢谢您对我们工作的关注，关于您所提到的问题：
1. 我们项目使用的数据集中，西安这个数据集的质量会比成都的差很多，在我们对原数据可视化的过程中也观察到很多您所说的情况。我们在别的使用该数据的研究中，可以对其进行简单的过滤（比如设定一个速度或者距离最大值）。
2. 你说的具体数值我太清楚具体是什么意思，如果是指轨迹点的经纬度的话那就不是，因为对于同一轨迹条件可以生成非常多样的轨迹。
3. 本论文使用的就是U-Net的结构设计，ResNet是每一个block的结构。
